# Generated by Django 4.1.4 on 2022-12-07 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=64, verbose_name='Название страны')),
                ('languages', models.CharField(max_length=255, verbose_name='Языки')),
            ],
        ),
    ]
